[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.2.0"
microlp = "0.2.11"
num = "0.4.3"
rayon = "1.10.0"
regex = "1.11.1"
tokio = { version = "1.42.0", features = ["full"] }
